{
"author": "",
"ua": "Mozilla/5.0 (Linux; Android 10; MI 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.104 Mobile Safari/537.36",
"homeUrl": "http://m.jrskan.com/",
"cateManual": {
"JRS赛事直播": "666"
},
"cateUrl": "http://m.jrskan.com/",
"cateVodNode": "//ul[@data-stype='zqlq']",
"cateVodName": "concat(/li[@class='lab_time']/text(),'-',/li[@class='lab_events']/span/text(),'dj')",
"cateVodId": "/li[@class='lab_channel']/a[1]/@href",
"cateVodIdR": "http://play.sportsteam268.com/play/steam(\\d+).html",
"cateVodImg": "/li[@class='lab_team_home']/span/img/@src",
"cateVodMark": "concat(//li[@class='lab_team_home']/strong/text(),'-',//li[@class='lab_team_away']/strong/text())",
"cate": "dj",
"dtUrl": "http://play.sportsteam357.com/play/steam{vid}.html",
"dtNode": "//ul[@data-stype='zqlq']",
"dtName": "/li[1]/span/text()",
"dtImg": "/li[3]/span/img/@src",
"dtCate": "/li[1]/span/text()",
"dtActor": "/li[1]/span/text()",
"dtDirector": "concat('勇士总冠军')",
"dtDirectorR": "",
"dtDesc": "concat(/li[3]/strong/text(),' VS ',/li[5]/strong/text())",
"dtFromNode": "//div[@class='sub_channel']",
"dtFromName": "concat('【推荐优先选择中文超清或中文高清直播源观看】')",
"dtFromNameR": "",
"dtUrlNode": "//div[@class='sub_channel']",
"dtUrlSubNode": "/a",
"dtUrlSub": "/ff",
"dtUrlId": "@data-play",
"dtUrlIdR": "/play/(\\S+)",
"dtUrlName": "/strong/text()",
"dtUrlNameR": "",
"playUrl": "http://play.sportsteam357.com/play/{playUrl}"
}
